<?php

namespace Core\Models\DbProtheus\Dbo;

class SB1010 extends AbstractModel
{
    public $timestamps = false;
    protected $connection = 'sqlsrv_dbProtheus';
    protected $table = 'dbo.SB1010';
    protected $primaryKey = 'R_E_C_N_O_';

    protected $fillable = [
        'B1_FILIAL','B1_GRUPO','B1_XDESGRU','B1_SUBGRU','B1_CODITE','B1_XSUBGRU','B1_COD','B1_DESC','B1_TIPO','B1_CC',
        'B1_POSIPI','B1_ESPECIE','B1_EX_NCM','B1_EX_NBM','B1_CONTA','B1_XCTADIG','B1_XCTAIMP','B1_XCTAPAR','B1_XCTASAL',
        'B1_UM','B1_LOCPAD','B1_BITMAP','B1_SEGUM','B1_PICM','B1_IPI','B1_ALIQISS','B1_CODISS','B1_CCCUSTO','B1_TE',
        'B1_TS','B1_PICMRET','B1_PICMENT','B1_IMPZFRC','B1_UCOM','B1_CONV','B1_TIPCONV','B1_ESTFOR','B1_ALTER','B1_QE'
        ,'B1_PRV1','B1_EMIN','B1_CUSTD','B1_UCALSTD','B1_UPRC','B1_MCUSTD','B1_PESO','B1_ESTSEG','B1_FORPRZ','B1_PE',
        'B1_LOJPROC','B1_TIPE','B1_LE','B1_LM','B1_TOLER','B1_ITEMCC','B1_FAMILIA','B1_UREV','B1_DATREF','B1_PROC',
        'B1_QB','B1_APROPRI','B1_DTREFP1','B1_TIPODEC','B1_ORIGEM','B1_CLASFIS','B1_FANTASM','B1_RASTRO','B1_FORAEST',
        'B1_CONINI','B1_CONTSOC','B1_COMIS','B1_CODBAR','B1_GRADE','B1_FORMLOT','B1_FPCOD','B1_MONO','B1_PERINV',
        'B1_CONTRAT','B1_DESC_P','B1_DESC_I','B1_DESC_GI','B1_GRTRIB','B1_MRP','B1_ANUENTE','B1_OPC','B1_CODOBS',
        'B1_NOTAMIN','B1_PRVALID','B1_FABRIC','B1_NUMCOP','B1_IRRF','B1_LOCALIZ','B1_OPERPAD','B1_PRODPAI','B1_VLREFUS',
        'B1_IMPORT','B1_DESPIMP','B1_SITPROD','B1_MODELO','B1_SETOR','B1_BALANCA','B1_TECLA','B1_TIPOCQ','B1_SOLICIT',
        'B1_DESBSE3','B1_BASE3','B1_GRUPCOM','B1_AGREGCU','B1_QUADPRO','B1_NALNCCA','B1_NALSH','B1_NUMCQPR',
        'B1_CONTCQP','B1_REVATU','B1_INSS','B1_CODEMB','B1_ESPECIF','B1_DATASUB','B1_MAT_PRI','B1_REDINSS',
        'B1_REDIRRF','B1_ALADI','B1_TAB_IPI','B1_GRUDES','B1_REDPIS','B1_REDCOF','B1_PCSLL','B1_PCOFINS','B1_PPIS',
        'B1_QTDSER','B1_MTBF','B1_MTTR','B1_FLAGSUG','B1_CLASSVE','B1_MIDIA','B1_QTMIDIA','B1_VLR_IPI','B1_ENVOBR',
        'B1_SERIE','B1_FAIXAS','B1_NROPAG','B1_ISBN','B1_TITORIG','B1_LINGUA','B1_EDICAO','B1_OBSISBN','B1_CLVL',
        'B1_ATIVO','B1_CORPRI','B1_CORSEC','B1_NICONE','B1_ATRIB1','B1_ATRIB2','B1_ATRIB3','B1_REGSEQ','B1_EMAX',
        'B1_PESBRU','B1_TIPCAR','B1_FRACPER','B1_REQUIS','B1_SELO','B1_LOTVEN','B1_OK','B1_USAFEFO','B1_INT_ICM','
        B1_VLR_ICM','B1_VLRSELO','B1_CNATREC','B1_TNATREC','B1_CLASSE','B1_CODNOR','B1_CPOTENC','B1_POTENCI',
        'B1_QTDACUM','B1_DIFCNAE','B1_DCR','B1_QTDINIC','B1_IAT','B1_IPPT','B1_MSBLQL','B1_SITTRIB','B1_DCI',
        'B1_VLR_PIS','B1_PMACNUT','B1_UMOEC','B1_QBP','B1_TALLA','B1_CODPROC','B1_CODQAD','B1_FECP','B1_ESCRIPI',
        'B1_COEFDCR','B1_PARCEI','B1_GDODIF','B1_VLCIF','B1_TPPROD','B1_GCCUSTO','B1_DTFIMNT','B1_CRICMS','B1_DTCORTE',
        'B1_DCRII','B1_DCRE','B1_REFBAS','B1_PMICNUT','B1_MARKUP','B1_GRPNATR','B1_FRETISS','B1_FUSTF','B1_PRODSBP','B1_PIS'
        ,'B1_VALEPRE','B1_LOTESBP','B1_TIPOBN','B1_UVLRC','B1_CALCFET','B1_ALFUMAC','B1_PRINCMG','B1_CARGAE','B1_REGRISS'
        ,'B1_CSLL','B1_PRODREC','B1_IVAAJU','B1_CODLAN','B1_RICM65','B1_COFINS','B1_DESBSE2','B1_FETHAB','B1_PR43080','
        B1_PRN944I','B1_ADMIN','B1_BASE2','B1_CRDEST','B1_SELOEN','B1_PRFDSUL','B1_RETOPER','B1_GARANT','B1_PAUTFET',
        'B1_TIPVEC','B1_VLR_COF','B1_BASE','B1_PERGART','B1_ESTRORI','B1_COLOR','B1_CNAE','B1_TRIBMUN','B1_CODANT',
        'B1_CHASSI','B1_CRICMST','B1_ALFECOP','B1_ALFECST','B1_FECOP','B1_VIGENC','B1_CRDPRES','B1_PRDORI','B1_AFETHAB',
        'B1_AFACS','B1_AFABOV','B1_TFETHAB','B1_REGESIM','B1_AJUDIF','B1_ALFECRN','B1_TPREG','B1_VEREAN','B1_RSATIVO',
        'B1_RPRODEP','B1_CFEM','B1_CFEMS','B1_CFEMA','B1_TPDP','B1_FECPBA','B1_MEPLES','B1_XUNIDAD','B1_XDTVALI',
        'B1_USERLGA','B1_XANYO','B1_XDIGITA','D_E_L_E_T_','R_E_C_N_O_','R_E_C_D_E_L_','B1_XCUSTO','B1_USERLGI',
        'B1_MSFIL','B1_MSEMP','B1_XFILAUT','B1_XPORTIF','B1_XDTPORT','B1_XSTATPO','B1_GRPCST','B1_PORCPRL',
        'B1_AFAMAD','B1_GRPTI','B1_CEST','B1_XPDIGIT','B1_01RFGRD','B1_01LNGRD','B1_01CLGRD','B1_01DREF','B1_01CODFO',
        'B1_01PRODP','B1_STATUS','B1_MSEXP','B1_01CAT1','B1_01CAT2','B1_01CAT3','B1_01CAT4','B1_01CAT5','B1_01CODMA',
        'B1_XNOMPRD','B1_XTITULO','B1_XSUBTIT','B1_XDESCRI','B1_XCARACT','B1_XALTPRD','B1_XLARPRD','B1_XPROPRD',
        'B1_XALTEMB','B1_XLAREMB','B1_XPROEMB','B1_XPRZADI','B1_XTPPROD','B1_XPRESEN','B1_XCODENQ','B1_XDESENQ',
        'B1_XNUM01','B1_XSTAPRD','B1_XTXT01','B1_XPERSON','B1_XDESPER','B1_XISBN','B1_XQTDMAX','B1_XESTMIN','B1_XEAN13',
        'B1_XYOUTUB','B1_XUSAECO','B1_XENVCAT','B1_XENVECO','B1_01CDANT','B1_01DTCAD','B1_XNUM02','B1_XCOMPOS',
        'B1_XCOD','B1_IDHIST','B1_PAFMD5','B1_AFASEMT','B1_AIMAMT','B1_TERUM','B1_AFUNDES','B1_INTEG','B1_HREXPO',
        'B1_MOPC','B1_IMPNCM'
    ];

}
