<?php

namespace Core\Models\DbProtheus\Dbo;

class SC6010 extends AbstractModel
{
    protected $connection = 'sqlsrv_dbProtheus';

    public $timestamps = false;
    protected $table = 'dbo.SC6010';
    //protected $primaryKey = 'idAccount';

    protected $fillable = [
        'C6_FILIAL','C6_ITEM','C6_PRODUTO','C6_UM','C6_QTDVEN','C6_PRCVEN','C6_VALOR','C6_QTDLIB','C6_QTDLIB2','C6_SEGUM','C6_TES',
        'C6_UNSVEN','C6_LOCAL','C6_CF','C6_QTDENT2','C6_QTDENT','C6_CLI','C6_DESCONT','C6_VALDESC','C6_ENTREG','C6_LA','C6_LOJA','C6_NOTA',
        'C6_SERIE','C6_DATFAT','C6_NUM','C6_COMIS1','C6_COMIS2','C6_COMIS3','C6_COMIS4','C6_COMIS5','C6_PEDCLI','C6_DESCRI','C6_PRUNIT',
        'C6_BLOQUEI','C6_RESERVA','C6_OP','C6_OK','C6_NFORI','C6_SERIORI','C6_ITEMORI','C6_IPIDEV','C6_IDENTB6','C6_BLQ','C6_PICMRET','C6_CODISS',
        'C6_GRADE','C6_ITEMGRD','C6_LOTECTL','C6_NUMLOTE','C6_DTVALID','C6_NUMORC','C6_CHASSI','C6_OPC','C6_LOCALIZ','C6_NUMSERI','C6_NUMOP',
        'C6_ITEMOP','C6_CLASFIS','C6_QTDRESE','C6_CONTRAT','C6_NUMOS','C6_NUMOSFA','C6_CODFAB','C6_LOJAFA','C6_ITEMCON','C6_TPOP','C6_REVISAO',
        'C6_SERVIC','C6_ENDPAD','C6_TPESTR','C6_CONTRT','C6_TPCONTR','C6_ITCONTR','C6_GEROUPV','C6_PROJPMS','C6_EDTPMS','C6_TASKPMS','C6_TRT','C6_QTDEMP',
        'C6_QTDEMP2','C6_PROJET','C6_ITPROJ','C6_POTENCI','C6_LICITA','C6_REGWMS','C6_MOPC','C6_NUMCP','C6_NUMSC','C6_ITEMSC','C6_SUGENTR','C6_ITEMED',
        'C6_ABSCINS','C6_ABATISS','C6_ABATMAT','C6_FUNRURA','C6_FETAB','C6_CODROM','C6_PROGRAM','C6_TURNO','C6_LOJDED','C6_CODLAN','C6_FORDED','C6_ITPC',
        'C6_PVCOMOP','C6_VDMOST','C6_FILPED','C6_PEDCOM','C6_VDOBS','C6_TPDEDUZ','C6_MOTDED','C6_VLDED','C6_VLNFD','C6_RATEIO','C6_SERDED','C6_PCDED','C6_NFDED',
        'C6_ITLPRE','C6_D1SERIE','C6_D1DOC','C6_CODLPRE','C6_D1ITEM','C6_VLIMPOR','C6_BASVEIC','C6_ABATINS','C6_TNATREC','C6_CNATREC','C6_GRPNATR','C6_DTFIMNT',
        'C6_ITEMPC','C6_NUMPCOM','C6_FCICOD','D_E_L_E_T_','R_E_C_N_O_','R_E_C_D_E_L_','C6_USERLGI','C6_USERLGA','C6_XPACOTE','C6_XRECPAI','C6_XPDIGIT','C6_HORENT',
        'C6_PMSID','C6_CODINF','C6_PEDVINC','C6_PRODFIN','C6_REVPROD','C6_XTICKET','C6_DATCPL','C6_HORCPL','C6_INTROT','C6_CATEG','C6_CTVAR','C6_PENE','C6_GCPLT',
        'C6_GCPIT','C6_ITEMGAR','C6_ORCGAR','C6_ALMTERC','C6_CCUSTO','C6_SOLCOM','C6_CC','C6_CONTA','C6_ITEMCTA','C6_CLVL','C6_CULTRA','C6_CSTPIS','C6_SDOCORI',
        'C6_SDOC','C6_SDOCDED','C6_SDOCSD1','C6_NRSEQCQ','C6_IPITRF','C6_TPPROD','C6_XSUBPCT','C6_TPREPAS','C6_XNOMEAL','C6_XKITPAC'

    ];

}