<?php

namespace Core\Models\DbProtheus\Dbo;

class SL1010 extends AbstractModel
{
    protected $connection = 'sqlsrv_dbProtheus';

    public $timestamps = false;
    protected $table = 'dbo.SL1010';
    //protected $primaryKey = 'idAccount';

    protected $fillable = [
        'L1_FILIAL','L1_NUM','L1_VEND','L1_COMIS','L1_CLIENTE','L1_LOJA','L1_TIPOCLI','L1_VLRTOT','L1_DESCONT','L1_VLRLIQ','L1_NROPCLI','L1_DTLIM','L1_DOC','L1_SERIE',
        'L1_PDV','L1_EMISNF','L1_VALBRUT','L1_VALMERC','L1_TIPO','L1_DESCNF','L1_OPERADO','L1_DINHEIR','L1_CHEQUES','L1_CARTAO','L1_CONVENI','L1_VALES','L1_FINANC',
        'L1_OUTROS','L1_ENTRADA','L1_JUROS','L1_PARCELA','L1_INTERV','L1_COND','L1_FORMA','L1_VALICM','L1_VALIPI','L1_VALISS','L1_TXDESC','L1_CONDPG','L1_FORMPG',
        'L1_CREDITO','L1_EMISSAO','L1_VEND2','L1_VEND3','L1_CONFVEN','L1_MULTNOT','L1_NUMCFIS','L1_FATOR','L1_IMPRIME','L1_VENDTEF','L1_DATATEF','L1_HORATEF',
        'L1_DOCTEF','L1_AUTORIZ','L1_DOCCANC','L1_DATCANC','L1_HORCANC','L1_INSTITU','L1_NSUTEF','L1_TIPCART','L1_VLRDEBI','L1_TEFSTAT','L1_ADMFIN','L1_STATUS','L1_HORA',
        'L1_OPERACA','L1_SITUA','L1_SUBSERI','L1_NUMORIG','L1_TXMOEDA','L1_MOEDA','L1_ENDCOB','L1_ENDENT','L1_TPFRET','L1_BAIRROC','L1_CEPC','L1_MUNC','L1_ESTC','L1_BAIRROE',
        'L1_CEPE','L1_MUNE','L1_ESTE','L1_FRETE','L1_SEGURO','L1_DESPESA','L1_PLIQUI','L1_PBRUTO','L1_VOLUME','L1_TRANSP','L1_ESPECIE','L1_MARCA','L1_NUMERO',
        'L1_PLACA','L1_UFPLACA','L1_BLCRED','L1_RESERVA','L1_VEICTIP','L1_VEIPESQ','L1_NRDOC','L1_TIPOJUR','L1_TROCO1','L1_EMPRES','L1_FILRES','L1_ORCRES','L1_TIPODES',
        'L1_FORCADA','L1_ESTACAO','L1_DOCPED','L1_CGCCART','L1_SERPED','L1_BRICMS','L1_CLIENT','L1_LOJENT','L1_NSO','L1_CONTRA','L1_LOGDESC','L1_ICMSRET','L1_PARCTEF',
        'L1_ABTOPCC','L1_VALPIS','L1_VALCOFI','L1_VALCSLL','L1_DIAFIXO','L1_NUMMOV','L1_NUMATEN','L1_PEDRES','L1_NUMORC','L1_TPORC','L1_CONTDOC','L1_CONTONF',
        'L1_CONTRG','L1_CONTCDC','L1_TABELA','L1_CGCCLI','L1_TEFBAND','L1_TRCXGER','L1_MIDIA','L1_TREFETI','L1_STATUES','L1_COODAV','L1_PAFMD5','L1_SERPDV','L1_CARTFID',
        'L1_VALIRRF','L1_IMPNF','L1_STORC','L1_PEDPRS','L1_ECFLAG','L1_XESCOLA','L1_XMATRIC','L1_XRESPON','L1_XIDRESP','L1_XNOMEAL','L1_XECPEDC','L1_XANOLET',
        'D_E_L_E_T_','R_E_C_N_O_','R_E_C_D_E_L_','L1_XIDORIG','L1_XTICKET','L1_XCELULA','L1_XCODSTA','L1_XDDD01','L1_XDDDCEL','L1_XDESTAT','L1_XDOCTRF',
        'L1_XMOVINT','L1_XMTCANC','L1_XNOMDES','L1_XNUMECL','L1_XNUMECO','L1_XOBSECO','L1_XSEDEX','L1_XSERTRF', 'L1_XTEL01','L1_XTRACKI','L1_XVLBXPV','L1_XDOCREM',
        'L1_XSERIRE','L1_XTPFRET','L1_ARRED','L1_VEND1','L1_VEND4','L1_VEND5','L1_USRST','L1_DTST','L1_HRST','L1_IFSANST','L1_IFSCDM1','L1_IFSCDM2','L1_DESCFIN','L1_MARCVEI',
        'L1_MODEVEI','L1_ANOFVEI','L1_PLACVEI','L1_RNVMVEI','L1_NUMFAB','L1_DVOSORI','L1_KEYNFCE','L1_DOCRPS','L1_SERRPS','L1_ORIGEM','L1_STBATCH','L1_ERROBTC','L1_NUMFRT',
        'L1_CODMNEG','L1_TIMEATE','L1_TIMEITE','L1_VLRARR','L1_VALINSS','L1_UMOVINF','L1_UMOV','L1_RECISS','L1_MENNOTA','L1_DOCCCF','L1_CONHTL','L1_ECPEDEC','L1_VALCOMI',
        'L1_ECRASTR','L1_ECSTATU','L1_VLRJUR','L1_LTRAN','L1_PRONFCE','L1_RESEHTL','L1_TOTEST','L1_TOTFED','L1_TOTMUN','L1_VEICUL1','L1_SERSAT','L1_ERGRVBT','L1_RETSFZ',
        'L1_SDOCSUB','L1_SDOCRPS','L1_SDOC','L1_SDOCPED','L1_XNFEREM','L1_XFILNFR','L1_XDTLIBD','L1_XHORAD','L1_XPROBLE','L1_XLOGIST','L1_XPEDLOG','L1_XNFLOG','L1_XNFDEV',
        'L1_XPVARME','L1_XNFARME','L1_XPVFAT','L1_XNFFAT','L1_XOBSERR','L1_XNF511','L1_XHORAIN','L1_XPRCNEW'
    ];

}
