<?php

namespace Core\Models\DbProtheus\Dbo;

class SL2010 extends AbstractModel
{
    public $timestamps = false;
    protected $connection = 'sqlsrv_dbProtheus';
    protected $table = 'dbo.SL2010';
    protected $primaryKey = 'R_E_C_N_O_';

    protected $fillable = [
        'L2_NUM', 'L2_PRODUTO', 'L2_ITEM', 'L2_DESCRI', 'L2_QUANT', 'L2_VRUNIT', 'L2_VLRITEM', 'L2_LOCAL', 'L2_UM',
        'L2_DESC', 'L2_VALDESC', 'L2_TES', 'L2_CF', 'L2_VENDIDO', 'L2_DOC', 'L2_SERIE', 'L2_PDV', 'L2_VALIPI',
        'L2_VALICM', 'L2_VALISS', 'L2_BASEICM', 'L2_TABELA', 'L2_STATUS', 'L2_EMISSAO', 'L2_DESCPRO', 'L2_CUSTO1',
        'L2_CUSTO2', 'L2_PRCTAB', 'L2_GRADE', 'L2_PREMIO', 'L2_FILIAL', 'L2_VEND', 'L2_LOTECTL', 'L2_NLOTE',
        'L2_LOCALIZ', 'L2_NSERIE', 'L2_BCONTA', 'L2_SITUA', 'L2_RESERVA', 'L2_LOJARES', 'L2_PEDFAT', 'L2_VALFRE',
        'L2_SEGURO', 'L2_DESPESA', 'L2_EMPRES', 'L2_FILRES', 'L2_ORCRES', 'L2_ICMSRET', 'L2_ENTREGA', 'L2_BRICMS',
        'L2_VALPIS', 'L2_VALCOFI', 'L2_VALCSLL', 'L2_VALPS2', 'L2_VALCF2', 'L2_BASEPS2', 'L2_BASECF2', 'L2_ALIQPS2',
        'L2_ALIQCF2', 'L2_ITEMSD1', 'L2_DTVALID', 'L2_SEGUM', 'L2_PEDRES', 'L2_FDTENTR', 'L2_CODCONT', 'L2_FDTMONT',
        'L2_CODREG', 'L2_VLDESRE', 'L2_TURNO', 'L2_NUMORIG', 'L2_SITTRIB', 'L2_VALEPRE', 'L2_CODLAN', 'L2_VDMOST', 'L2_VDOBS',
        'L2_MARCA', 'L2_TIPO', 'L2_DESCORC', 'L2_MODELO', 'L2_ESPECIE', 'L2_QUALIDA', 'L2_PEDSC5', 'L2_ITESC6',
        'L2_SEQUEN', 'L2_SOLCOM', 'L2_SERPDV', 'L2_CONTDOC', 'L2_PAFMD5', 'L2_CODLPRE', 'L2_GARANT', 'L2_ITLPRE',
        'L2_MSMLPRE', 'L2_REMLPRE', 'L2_DTSDFID', 'L2_NUMCFID', 'L2_VLRCFID', 'L2_PROCFID', 'L2_ECPRESN', 'L2_ECSEDEX',
        'L2_PEDPRS', 'L2_ECMSGPR', 'D_E_L_E_T_', 'R_E_C_N_O_', 'R_E_C_D_E_L_', 'L2_XRECPAI', 'L2_XDESTAT', 'L2_XPRODTP', '
        L2_XPRZENT', 'L2_XSTATIT', 'L2_MESREC', 'L2_CODBAR', 'L2_ORIGEM', 'L2_MODBC', 'L2_CODISS', 'L2_POSIPI', 'L2_LEGCOD',
        'L2_ITEMNF', 'L2_VALACRS', 'L2_VLGAPRO', 'L2_VLIMPOR', 'L2_BLEST', 'L2_TOTIMP', 'L2_FCICOD', 'L2_CLASFIS', 'L2_DOCPED',
        'L2_SERPED', 'L2_CLIENT', 'L2_CLILOJA', 'L2_ALIQCOF', 'L2_ALIQISS', 'L2_ALIQPIS', 'L2_ALQCSLL', 'L2_ALQIRRF', 'L2_BASCSLL',
        'L2_BASECOF', 'L2_BASEISS', 'L2_BASEPIS', 'L2_BASIRRF', 'L2_CCUSTO', 'L2_CLVL', 'L2_ITEMCC', 'L2_PICM', 'L2_VALIRRF',
        'L2_DTUMOV', 'L2_HRUMOV', 'L2_REV', 'L2_TOTFED', 'L2_FLUMOV', 'L2_VLTROCA', 'L2_INDPAR', 'L2_CEST', 'L2_PREDIC',
        'L2_ALQFECP', 'L2_VALFECP', 'L2_ECVALOR', 'L2_KIT', 'L2_CNAE', 'L2_SDOC', 'L2_SDOCPED', 'L2_TOTMUN', 'L2_TOTEST',
        'L2_ITEMCOB', 'L2_PRDCOBE', 'L2_QTDEDEV', 'L2_ITEMGAR', 'L2_GARDEV', 'L2_XSUBPCT', 'L2_XDTLIBD', 'L2_XHORAD',
        'L2_XNOMEAL', 'L2_XKITPAC', 'L2_XCODLIB', 'L2_XENVLIB'
    ];

}
